CREATE TABLE [dbo].[PLAYER_CONTRACT] (
    [ID_PLAYER]       NUMERIC (10) NOT NULL,
    [CONTRACT_NUMBER] NUMERIC (10) NOT NULL,
    [START_DATE]      DATE         NOT NULL,
    [END_DATE]        DATE         NOT NULL,
    CONSTRAINT [PK_CONTRACT_NUMBER] PRIMARY KEY CLUSTERED ([CONTRACT_NUMBER] ASC),
    CONSTRAINT [CK_CONTRACT] CHECK ([END_DATE]>[START_DATE]),
    CONSTRAINT [FK_CONTRACT_REF_PLAYER] FOREIGN KEY ([ID_PLAYER]) REFERENCES [dbo].[PLAYER_REGISTRATION] ([ID_PLAYER])
);

