CREATE TABLE [dbo].[PLAYER_REGISTRATION] (
    [ID_PLAYER] NUMERIC (10)  NOT NULL,
    [NAME]      VARCHAR (100) NOT NULL,
    [TEAM]      VARCHAR (50)  NOT NULL,
    [AGE]       NUMERIC (10)  NOT NULL,
    [COUNTRY]   VARCHAR (20)  NOT NULL,
    [NICKNAME]  VARCHAR (20)  NULL,
    CONSTRAINT [PK_ID_PLAYER] PRIMARY KEY CLUSTERED ([ID_PLAYER] ASC)
);

