CREATE PROCEDURE PR_SELECT_PLAYER_DATA
AS

SELECT PLAYER_REGISTRATION.NAME,
	   PLAYER_REGISTRATION.NICKNAME,
	   PLAYER_REGISTRATION.TEAM,
	   PLAYER_CONTRACT.CONTRACT_NUMBER,
	   PLAYER_CONTRACT.START_DATE,
	   PLAYER_CONTRACT.END_DATE		
FROM PLAYER_REGISTRATION (NOLOCK)
INNER JOIN PLAYER_CONTRACT (NOLOCK) ON PLAYER_REGISTRATION.ID_PLAYER = PLAYER_CONTRACT.ID_PLAYER
ORDER BY START_DATE DESC